kind: pipeline
name: default

steps:
- name: test
  image: node
  commands:
  - npm install
  - npm test
  environment:
    USERNAME:
      from_secret: docker_username
    PASSWORD:
      from_secret: docker_password
  when:
    branch:
    - master
