language: node_js
matrix:
  include:
    - node_js: 16
    - node_js: 14
    - node_js: 12
  allow_failures:
    - node_js: 16
    - node_js: 12
before_install:
  - sudo apt-get update
  - sudo apt-get install python3.9
install:
  - npm install
  - npm install --only=dev
script:
  - npm test
  - npm run coverage
  - npm run build
cache:
  directories:
  - "node_modules"
branches:
  only:
  - master
  - develop
  - alpha
  - beta
